name: CI

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        requirements: ['-r requirements.txt']
        include:
          # historical requirements
          - name: "2020-early dependencies"
            requirements: 2020-early.txt
            pytest_flags: --ignore=siuba/dply/forcats.py siuba
            python-version: 3.6
          # current
          - name: "2020-mid dependencies"
            python-version: 3.8
            requirements: 2020-mid.txt
          - name: "2021-mid dependencies"
            python-version: 3.8
            requirements: 2021-mid.txt
          - name: "2022-early dependencies"
            python-version: 3.8
            requirements: 2022-early.txt
          - name: "2022-early dependencies (py 3.10)"
            python-version: 3.10
            requirements: 2022-early.txt
            latest: true

    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose
        run: |
          docker-compose up --build -d
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ci/deps/"$REQUIREMENTS"
          python -m pip install -r requirements-test.txt
          python -m pip install .
        env:
          REQUIREMENTS: ${{ matrix.requirements }}
      - name: Test with pytest
        run: |
          make test-travis
        env:
          SB_TEST_PGPORT: 5432
          PYTEST_FLAGS: ${{ matrix.pytest_flags }}

      # optional step for running bigquery tests ----
      - name: Set up Cloud SDK
        if: ${{(contains(github.ref, 'bigquery') || contains(github.ref, 'refs/tags')) && matrix.latest}}
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: siuba-tests
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Test bigquery
        if: ${{(contains(github.ref, 'bigquery') || contains(github.ref, 'refs/tags')) && matrix.latest}}
        run: |
          pip install git+https://github.com/googleapis/python-bigquery-sqlalchemy.git pandas-gbq==0.15.0

  test-bigquery:
    name: "Test BigQuery"
    runs-on: ubuntu-latest
    if: contains(github.ref, 'bigquery') || contains(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-test.txt
          python -m pip install git+https://github.com/machow/pybigquery.git pandas-gbq==0.15.0
          python -m pip install .
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: siuba-tests
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Test with pytest
        run: |
          pytest siuba -m bigquery
        env:
          SB_TEST_BQDATABASE: "ci_github"

  deploy:
    name: "Deploy to PyPI"
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [checks, test-bigquery]
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Build Package"
        run:
          python setup.py build sdist

      # test deploy ----
      - name: "Test Deploy to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.event.release.name, 'TEST')
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      # prod deploy ----
      - name: "Deploy to PyPI"
        uses: pypa/gh-action-pypi-publish@master
        if: "!startsWith(github.event.release.name, 'TEST')"
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
